services:
  web:
    build: ./deploy/api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/api:rwo
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /api
  
  postgres:
    image: postgres:15.2
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 4s
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
